[package]
name = "cofswalk"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

[[bin]]
name = "example"
path = "src/example.rs"

[dependencies]
futures-core = "0.3.31"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
